watch_gradients: false
num_epochs: 20
model: tcmm
lag: 2
monitor_checkpoint_based_on: likelihood
#checkpoint_path: "logs\\mcd_netsim_15_200_permuted_seed_0_20250318_11_10_08\\version_0\\checkpoints\\last.ckpt"
hypernet:
  _target_: src.modules.GATlinear_MultiTemporalHyperNet.MultiTemporalHyperNet
  order: linear
  num_bins: 8
  skip_connection: true
  embedding_dim: 256

# decoder options
decoder:
  _target_: src.modules.TCMMDecoder.SpatiotemporalGAT
  embedding_dim: 256

trainer:
  _target_: src.model.TCMMTrainer.TCMMTrainer
  _partial_: true
  shuffle: false
  batch_size: 128
  #sparsity_factor: 3
  sparsity_factor: 15
  likelihood_loss: flow
  matrix_temperature: 0.25
  threeway_graph_dist: True
  training_procedure: auglag
  skip_auglag_epochs: 0
  graph_selection_prior_lambda: 0.0
  init_logits: [-5, -5, 0]
  #num_graphs: 1
  num_graphs: 3
  use_correct_mixture_index: false
  use_true_graph: false
  disable_inst: false
  #log_num_unique_graphs: True

auglag_config:
  _target_: src.training.auglag.AugLagLRConfig

  lr_update_lag: 500
  lr_update_lag_best: 500
  lr_init_dict:
    vardist: 0.01
    functional_relationships: 0.001
    noise_dist: 0.001
    mixing_probs: 0.01

  aggregation_period: 20
  lr_factor: 0.1
  max_lr_down: 3
  penalty_progress_rate:  0.65
  safety_rho: 1e13
  safety_alpha: 1e13
  inner_early_stopping_patience: 1500
  max_outer_steps: 200
  patience_penalty_reached: 250
  patience_max_rho: 50
  penalty_tolerance: 1e-8
  max_inner_steps: 2000
  force_not_converged: false
  init_rho: 1
  init_alpha: 0